### ISSUE TITLE
Converter para site dinâmico

### ISSUE THREAD

**Issue by fabiommendes** [pyladiesdf/website#11]
Converter site para tecnologia dinâmica com Django no backend.

* Backend em Django
* Opções para front:
  * Templates + Sass
   * Framework JS (React, Vue?)
   * Frontend não-js ELM :)

**Comment by fabiommendes** [comment]
Elm é uma linguagem funcional para front-end. Se tiver interesse posso treinar o ramo não-Python das Pyladies

**Comment by fabiommendes** [comment]
ELM (http://elm-lang.org/) é uma linguagem funcional para front-end inspirada em Haskell. Se tiver interesse posso treinar o ramo não-Python das Pyladies

**Comment by Dayof** [comment]
Quebramos essa issue em outras menores :heart:
