### ISSUE TITLE
Trocar cor do rodape e links para cores do logo

### ISSUE THREAD

**Issue by taniaa** [pyladiesdf/website#51]
Como o site foi um fork do pyladies global, ainda esta com umas partes rosa pink. A ideia eh o site refletir as cores do logo. Roxo predominante do logo com amarelo do site ia dar um contraste legal.

**Comment by lenamiroux** [comment]
Sugiro um esquema assim:

[Material Design Color Tool](https://material.io/resources/color/#!/?view.left=0&view.right=1&primary.color=6A1B9A&secondary.color=FDD835)

![image](https://user-images.githubusercontent.com/12610282/95983125-7bcc4580-0df7-11eb-8eed-8dcf3e3d7274.jpeg)
![image](https://user-images.githubusercontent.com/12610282/95983137-81299000-0df7-11eb-847c-9f5bf2638bdf.jpeg)

![image](https://user-images.githubusercontent.com/12610282/95983515-1d539700-0df8-11eb-87d1-4284d497d1a4.jpeg)

**Comment by lenamiroux** [comment]
Pq o amarelo no rodapé fica muito claro:

![image](https://user-images.githubusercontent.com/12610282/95983720-82a78800-0df8-11eb-8abb-744f8ac03db3.jpeg)
![image](https://user-images.githubusercontent.com/12610282/95983733-889d6900-0df8-11eb-8c0b-7d33670bdb4b.jpeg)

![image](https://user-images.githubusercontent.com/12610282/95983785-9b17a280-0df8-11eb-8c89-3a0dffc35928.jpeg)
