### ISSUE TITLE
Trocar favicon de boneca vermelha

### ISSUE THREAD

**Issue by taniaa** [pyladiesdf/website#53]
O site esta apresentando a boneca original vermelha. Trocar pela logo de boneca roxa com flor amarela.

**Comment by emmenezes** [comment]
Vou fazer isso!

**Comment by taniaa** [comment]
Obrigadam @emmenezes! 

@Dayof @naiieandrade @BrunaNayara dei um merge neste PR do favicon. Com que frequencia as alteracoes vao pra producao? Podem dar uma olhada nisso? Obrigada!
